{
    "openapi": "3.0.3",
    "info": {
        "title": "GoLomba RESTful API",
        "version": "1.5",
        "description": "API contract for GoLomba RESTful API",
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        }
    },
    "servers": [
        {
            "description": "GoLomba API server",
            "url": "https://{environment}.server/api/v1",
            "variables": {
                "environment": {
                    "description": "Environment",
                    "default": "dev",
                    "enum": ["dev", "prod"]
                }
            }
        }
    ],
    "externalDocs": {
        "description": "Find out more about GoLomba",
        "url": "https://golomba.io"
    },
    "paths": {
        "/competitions": {
            "get": {
                "tags": ["competitions"],
                "summary": "Get all competitions",
                "description": "Get all competitions",
                "operationId": "getCompetitions",
                "parameters": [
                    {
                        "name": "search",
                        "in": "query",
                        "description": "Search by name or description",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        }
                    },
                    {
                        "name": "education_level",
                        "in": "query",
                        "description": "Education level",
                        "required": false,
                        "schema": {
                            "$ref": "#/components/schemas/education_level-params",
                            "nullable": true
                        }
                    },
                    {
                        "name": "tags",
                        "in": "query",
                        "description": "Tags competition category separated by comma, e.g. tag1,tag2",
                        "required": false,
                        "schema": {
                            "type": "array",
                            "nullable": true,
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get all competitions",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/competitions"
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success response get all Competitions",
                                        "value": [
                                            {
                                                "id": 1,
                                                "name": "Competition 1",
                                                "description": "Competition 1 description",
                                                "image": "https://golomba.io/images/competition1.jpg",
                                                "tags": ["tag1", "tag2"],
                                                "education_level_id": 0,
                                                "start_date": "2021-01-01T00:00:00Z",
                                                "end_date": "2021-01-31T00:00:00Z"
                                            },
                                            {
                                                "id": 2,
                                                "name": "Competition 2",
                                                "description": "Competition 2 description",
                                                "image": "https://golomba.io/images/competition2.jpg",
                                                "tags": ["tag3", "tag4"],
                                                "education_level_id": 1,
                                                "start_date": "2021-02-01T00:00:00Z",
                                                "end_date": "2021-02-28T00:00:00Z"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error404"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error500"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": ["competitions"],
                "summary": "Create a new competition",
                "description": "Create a new competition in database",
                "operationId": "createCompetition",
                "requestBody": {
                    "description": "Competition object that needs to be added to the store",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/competitions"
                            },
                            "examples": {
                                "competition 1": {
                                    "$ref": "#/components/examples/competition1"
                                },
                                "competition 2": {
                                    "$ref": "#/components/examples/competition2"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success create a new competition",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "description": "Success create competition"
                                        },
                                        "competition": {
                                            "$ref": "#/components/schemas/competitions"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error400"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error401"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error500"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/competitions/{competitionId}": {
            "put": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": ["competitions"],
                "summary": "Update existing competition",
                "description": "Update existing competition in database",
                "operationId": "updateCompetition",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/competitionId"
                    }
                ],
                "requestBody": {
                    "description": "Competition object that needs to be added to the store",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/competitions"
                            },
                            "examples": {
                                "competition 1": {
                                    "$ref": "#/components/examples/competition1"
                                },
                                "competition 2": {
                                    "$ref": "#/components/examples/competition2"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success update existing competition",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "description": "Success update competition"
                                        },
                                        "competition": {
                                            "$ref": "#/components/schemas/competitions"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error400"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error401"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error500"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": ["competitions"],
                "summary": "Delete existing competition",
                "description": "Delete existing competition in database",
                "operationId": "deleteCompetition",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/competitionId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success delete existing competition",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/delete"
                                },
                                "examples": {
                                    "competition 1": {
                                        "description": "Example success response delete competition",
                                        "value": {
                                            "success": true,
                                            "competition": {
                                                "id": 1,
                                                "name": "Competition 1",
                                                "description": "Competition 1 description",
                                                "image": "https://golomba.io/images/competition1.jpg",
                                                "tags": ["tag1", "tag2"],
                                                "education_level": "high_school",
                                                "start_date": "2021-01-01T00:00:00Z",
                                                "end_date": "2021-01-31T00:00:00Z"
                                            }
                                        }
                                    },
                                    "competition 2": {
                                        "description": "Example success response delete competition",
                                        "value": {
                                            "success": true,
                                            "competition": {
                                                "id": 2,
                                                "name": "Competition 2",
                                                "description": "Competition 2 description",
                                                "image": "https://golomba.io/images/competition2.jpg",
                                                "tags": ["tag3", "tag4"],
                                                "education_level": "university",
                                                "start_date": "2021-01-01T00:00:00Z",
                                                "end_date": "2021-01-31T00:00:00Z"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error400"
                                    }
                                }
                            }
                        }
                    },

                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error401"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error500"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": ["users"],
                "summary": "User Register",
                "description": "Register to the application with username and password",
                "operationId": "register",
                "requestBody": {
                    "required": true,
                    "description": "User object that needs to register",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "required": ["username", "email", "password"]
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Register successful. Returns an access token.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "description": "Success register"
                                        },
                                        "message": {
                                            "type": "string",
                                            "description": "Success register"
                                        }
                                    }
                                },
                                "example": {
                                    "success": "true",
                                    "message": "Success register your account. Please login to continue."
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error400"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error500"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": ["users"],
                "summary": "User Login",
                "description": "Login to the application with username and password",
                "operationId": "login",
                "requestBody": {
                    "required": true,
                    "description": "User object that needs to check login",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "username": {
                                        "type": "string",
                                        "description": "Username access to application"
                                    },
                                    "password": {
                                        "type": "string",
                                        "description": "Password access to application"
                                    }
                                },
                                "required": ["username", "password"]
                            },
                            "examples": {
                                "login": {
                                    "summary": "Example login",
                                    "value": {
                                        "username": "userlogin",
                                        "password": "user432"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Login successful. Returns an access token.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "access_token": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "summary": "Example error unauthorized",
                                        "value": {
                                            "code": 401,
                                            "message": "Unauthorized. invalid credentials."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found. User with the provided username does not exist.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error500"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/testimonials": {
            "get": {
                "tags": ["testimonials"],
                "summary": "Get all testimonials",
                "description": "Get all testimonials from database",
                "operationId": "getTestimonials",
                "responses": {
                    "200": {
                        "description": "Success get all testimonials",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/testimonial"
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success response get all testimonials",
                                        "value": [
                                            {
                                                "id": 1,
                                                "user_id": 1,
                                                "message": "Testimonial 1",
                                                "stars": 5
                                            },
                                            {
                                                "id": 2,
                                                "user_id": 2,
                                                "message": "Testimonial 2",
                                                "stars": 4
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error404"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error500"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags": ["testimonials"],
                "summary": "Submit a testimonial",
                "description": "Use this endpoint to submit a testimonial.",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/testimonial"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Testimonial submitted successfully.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "description": "Success submit testimonial"
                                        },
                                        "testimonial": {
                                            "$ref": "#/components/schemas/testimonial"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request. Invalid input data.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error400"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found. User with the provided user_id does not exist.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error404"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "error": {
                                        "$ref": "#/components/examples/error500"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        },
        "parameters": {
            "competitionId": {
                "name": "competitionId",
                "in": "path",
                "description": "Competition ID",
                "required": true,
                "schema": {
                    "type": "number",
                    "format": "int64",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples": {
                    "competitionId": {
                        "description": "Example competition ID",
                        "value": 1
                    },
                    "competitionId2": {
                        "description": "Example competition ID",
                        "value": 2
                    }
                }
            }
        },
        "schemas": {
            "testimonial": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "description": "The ID of the testimonial."
                    },
                    "user_id": {
                        "type": "integer",
                        "description": "The ID of the user who submitted the testimonial."
                    },
                    "message": {
                        "type": "string",
                        "description": "The testimonial message."
                    },
                    "stars": {
                        "type": "integer",
                        "description": "The number of stars given to the testimonial."
                    }
                }
            },
            "education_level-params": {
                "type": "string"
            },
            "successCreateCompetition": {},
            "delete": {
                "type": "object",
                "properties": {
                    "success": {
                        "type": "boolean",
                        "description": "Success delete competition"
                    },
                    "competition": {
                        "$ref": "#/components/schemas/competitions"
                    }
                }
            },
            "competitions": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number",
                        "format": "int64",
                        "description": "Competition ID"
                    },
                    "name": {
                        "type": "string",
                        "description": "Competition name"
                    },
                    "description": {
                        "type": "string",
                        "description": "Competition description"
                    },
                    "image": {
                        "type": "string",
                        "description": "Competition image URL"
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "Competition tags"
                    },
                    "education_level_id": {
                        "type": "number",
                        "format": "int64",
                        "description": "Education level ID"
                    },
                    "start_date": {
                        "type": "string",
                        "format": "date-time",
                        "description": "Competition start date"
                    },
                    "end_date": {
                        "type": "string",
                        "format": "date-time",
                        "description": "Competition end date"
                    }
                }
            },
            "education_level": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number",
                        "format": "int64",
                        "description": "Education level ID"
                    },
                    "name": {
                        "type": "string",
                        "description": "Education level name"
                    }
                }
            },
            "error": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "number",
                        "format": "int64",
                        "description": "Error code"
                    },
                    "message": {
                        "type": "string",
                        "description": "Error message"
                    }
                }
            }
        },
        "examples": {
            "error400": {
                "summary": "error bad request",
                "value": {
                    "code": 400,
                    "message": "Bad request"
                }
            },
            "error401": {
                "summary": "error unauthorized",
                "value": {
                    "code": 401,
                    "message": "Unauthorized"
                }
            },
            "error404": {
                "summary": "error not found",
                "value": {
                    "code": 404,
                    "message": "Not found"
                }
            },
            "error500": {
                "summary": "error internal server error",
                "value": {
                    "code": 500,
                    "message": "Internal Server Error"
                }
            },
            "competition1": {
                "summary": "Example competition 1 response",
                "value": {
                    "id": 1,
                    "name": "Competition 1",
                    "description": "Competition 1 description",
                    "image": "https://golomba.io/images/competition1.jpg",
                    "tags": ["tag1", "tag2"],
                    "education_level_id": 0,
                    "start_date": "2021-01-01T00:00:00Z",
                    "end_date": "2021-01-31T00:00:00Z"
                }
            },
            "competition2": {
                "summary": "Example competition 2 response",
                "value": {
                    "id": 2,
                    "name": "Competition 2",
                    "description": "Competition 2 description",
                    "image": "https://golomba.io/images/competition2.jpg",
                    "tags": ["tag3", "tag4"],
                    "education_level_id": 1,
                    "start_date": "2021-02-01T00:00:00Z",
                    "end_date": "2021-02-28T00:00:00Z"
                }
            }
        }
    }
}
